### ISSUE TITLE
Error: Cannot find module 'bs-ink/src/ReasonInk.bs.js'

### ISSUE THREAD

**Issue by philipbalbas** [cometkim/reason-ink#6]
HI @cometkim , I'm using reason-ink 2.0.0 and it seems that the compiled bs file is still requiring dependencies from the "bs-ink" module

![image](https://user-images.githubusercontent.com/14971706/82523805-cce54f80-9b5f-11ea-83e1-0c3a4b0c52c9.png)

**Comment by cometkim** [comment]
Ah, thank you for reporting this @philipbalbas, had a mistake in publishing package.

I will fix it today.

**Comment by cometkim** [comment]
Fixed in v2.0.1. Thanks
